apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: demoapp-operator
  template:
    metadata:
      labels:
        name: demoapp-operator
    spec:
      serviceAccountName: demoapp-operator
      containers:
        - name: demoapp-operator
          # Replace this with the built image name
          image: quay.io/wtwilight/demoapp-operator
          command:
          - demoapp-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "demoapp-operator"
